version: 2.1

jobs:
  build:
    image: maven:3.6.3-jdk-11
    stage: build
    script:
      - mvn clean
      - mvn compile
      - mvn test

  deploy:
    image: maven:3.6.3-jdk-11
    stage: deploy
    script:
      - mvn install
      
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          needs: [build]