image: maven:3.6.3-jdk-11

stages:
  - build
  - deploy

before script:
  - mvn clean
  - mvn install

build:
  stage: build
  script:
    - mvn compile
    - mvn test

deploy:
  stage: deploy
  script:
    - mvn install